# Generated by Django 4.2.27 on 2025-12-13 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='년도')),
                ('month', models.IntegerField(verbose_name='월')),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='청구 금액')),
                ('paid_amount', models.PositiveIntegerField(default=0, verbose_name='납부 금액')),
                ('status', models.CharField(choices=[('paid', '완납'), ('unpaid', '미납'), ('partial', '부분납')], default='unpaid', max_length=20, verbose_name='납부 상태')),
                ('payment_method', models.CharField(blank=True, choices=[('cash', '현금'), ('card', '카드'), ('transfer', '계좌이체'), ('other', '기타')], max_length=20, verbose_name='결제 방식')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='납부일')),
                ('note', models.TextField(blank=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='students.student', verbose_name='학생')),
            ],
            options={
                'verbose_name': '수납',
                'verbose_name_plural': '수납 목록',
                'ordering': ['-year', '-month', 'student__name'],
                'unique_together': {('student', 'year', 'month')},
            },
        ),
    ]
