# Generated by Django 4.2.27 on 2025-12-16 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='할인명')),
                ('discount_type', models.CharField(choices=[('sibling', '형제 할인'), ('scholarship', '장학금'), ('early_bird', '조기 등록 할인'), ('referral', '추천인 할인'), ('other', '기타')], max_length=20, verbose_name='할인 유형')),
                ('discount_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='할인율 (%)')),
                ('discount_amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='할인 금액')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='시작일')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='종료일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '할인 정책',
                'verbose_name_plural': '할인 정책 목록',
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_amount', models.PositiveIntegerField(verbose_name='환불 금액')),
                ('reason', models.TextField(verbose_name='환불 사유')),
                ('status', models.CharField(choices=[('pending', '대기'), ('approved', '승인'), ('completed', '완료'), ('rejected', '거절')], default='pending', max_length=20, verbose_name='상태')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='요청일')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='처리일')),
                ('processed_by', models.CharField(blank=True, max_length=100, verbose_name='처리자')),
                ('bank_name', models.CharField(blank=True, max_length=50, verbose_name='은행명')),
                ('account_number', models.CharField(blank=True, max_length=50, verbose_name='계좌번호')),
                ('account_holder', models.CharField(blank=True, max_length=50, verbose_name='예금주')),
                ('note', models.TextField(blank=True, verbose_name='비고')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.payment', verbose_name='관련 수납')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='students.student', verbose_name='학생')),
            ],
            options={
                'verbose_name': '환불',
                'verbose_name_plural': '환불 목록',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_date', models.DateField(auto_now_add=True, verbose_name='적용일')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='비고')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.discount', verbose_name='할인 정책')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='students.student', verbose_name='학생')),
            ],
            options={
                'verbose_name': '학생 할인',
                'verbose_name_plural': '학생 할인 목록',
                'unique_together': {('student', 'discount')},
            },
        ),
    ]
