# Generated by Django 4.2.27 on 2025-12-13 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('gender', models.CharField(blank=True, choices=[('M', '남'), ('F', '여')], max_length=1, verbose_name='성별')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='생년월일')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='연락처')),
                ('parent_name', models.CharField(blank=True, max_length=50, verbose_name='학부모 이름')),
                ('parent_phone', models.CharField(blank=True, max_length=20, verbose_name='학부모 연락처')),
                ('parent_relation', models.CharField(blank=True, help_text='예: 어머니, 아버지', max_length=20, verbose_name='관계')),
                ('status', models.CharField(choices=[('enrolled', '재원'), ('paused', '휴원'), ('withdrawn', '퇴원')], default='enrolled', max_length=20, verbose_name='재원 상태')),
                ('enrollment_date', models.DateField(blank=True, null=True, verbose_name='등록일')),
                ('withdrawal_date', models.DateField(blank=True, null=True, verbose_name='퇴원일')),
                ('school_name', models.CharField(blank=True, max_length=100, verbose_name='학교명')),
                ('grade', models.CharField(blank=True, max_length=20, verbose_name='학년')),
                ('note', models.TextField(blank=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('assigned_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='classes.class', verbose_name='반')),
            ],
            options={
                'verbose_name': '학생',
                'verbose_name_plural': '학생 목록',
                'ordering': ['name'],
            },
        ),
    ]
