# Generated by Django 4.2.27 on 2025-12-16 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waitlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('phone', models.CharField(max_length=20, verbose_name='연락처')),
                ('parent_name', models.CharField(blank=True, max_length=50, verbose_name='학부모 이름')),
                ('parent_phone', models.CharField(blank=True, max_length=20, verbose_name='학부모 연락처')),
                ('desired_start_date', models.DateField(blank=True, null=True, verbose_name='희망 시작일')),
                ('status', models.CharField(choices=[('waiting', '대기 중'), ('contacted', '연락 완료'), ('enrolled', '등록 완료'), ('cancelled', '취소')], default='waiting', max_length=20, verbose_name='상태')),
                ('priority', models.PositiveIntegerField(default=0, verbose_name='우선순위')),
                ('note', models.TextField(blank=True, verbose_name='메모')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('contacted_at', models.DateTimeField(blank=True, null=True, verbose_name='연락일')),
                ('desired_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.class', verbose_name='희망 반')),
            ],
            options={
                'verbose_name': '대기자',
                'verbose_name_plural': '대기자 목록',
                'ordering': ['priority', 'registered_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsultLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consult_type', models.CharField(choices=[('phone', '전화 상담'), ('visit', '방문 상담'), ('online', '온라인 상담'), ('other', '기타')], max_length=20, verbose_name='상담 유형')),
                ('consult_date', models.DateField(verbose_name='상담일')),
                ('counselor', models.CharField(max_length=50, verbose_name='상담자')),
                ('topic', models.CharField(max_length=200, verbose_name='상담 주제')),
                ('content', models.TextField(verbose_name='상담 내용')),
                ('action_plan', models.TextField(blank=True, verbose_name='후속 조치')),
                ('next_consult_date', models.DateField(blank=True, null=True, verbose_name='다음 상담 예정일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consult_logs', to='students.student', verbose_name='학생')),
            ],
            options={
                'verbose_name': '상담 일지',
                'verbose_name_plural': '상담 일지 목록',
                'ordering': ['-consult_date'],
            },
        ),
    ]
