# Generated by Django 4.2.27 on 2025-12-13 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='반 이름')),
                ('subject', models.CharField(blank=True, max_length=100, verbose_name='과목')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('weekdays', models.CharField(blank=True, help_text='쉼표로 구분 (예: mon,wed,fri)', max_length=50, verbose_name='수업 요일')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='시작 시간')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='종료 시간')),
                ('max_students', models.PositiveIntegerField(default=20, verbose_name='정원')),
                ('monthly_fee', models.PositiveIntegerField(default=0, verbose_name='월 수강료')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='teachers.teacher', verbose_name='담당 강사')),
            ],
            options={
                'verbose_name': '반',
                'verbose_name_plural': '반 목록',
                'ordering': ['name'],
            },
        ),
    ]
