# Generated by Django 4.2.27 on 2025-12-16 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='설정 키')),
                ('value', models.TextField(verbose_name='설정 값')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='설명')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='수정자')),
            ],
            options={
                'verbose_name': '시스템 설정',
                'verbose_name_plural': '시스템 설정 목록',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('message', models.TextField(verbose_name='내용')),
                ('notification_type', models.CharField(choices=[('info', '정보'), ('warning', '경고'), ('success', '성공'), ('error', '오류')], default='info', max_length=20, verbose_name='유형')),
                ('is_read', models.BooleanField(default=False, verbose_name='읽음 여부')),
                ('link', models.CharField(blank=True, max_length=200, verbose_name='링크')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='읽은 시각')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '알림',
                'verbose_name_plural': '알림 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('sms', 'SMS'), ('kakao', '카카오 알림톡'), ('email', '이메일')], max_length=20, verbose_name='메시지 유형')),
                ('recipient', models.CharField(max_length=100, verbose_name='수신자')),
                ('recipient_phone', models.CharField(blank=True, max_length=20, verbose_name='수신 번호')),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('status', models.CharField(choices=[('pending', '대기'), ('sent', '발송 완료'), ('failed', '발송 실패'), ('retry', '재시도')], default='pending', max_length=20, verbose_name='상태')),
                ('error_message', models.TextField(blank=True, verbose_name='오류 메시지')),
                ('retry_count', models.PositiveIntegerField(default=0, verbose_name='재시도 횟수')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='발송 시각')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='발송자')),
            ],
            options={
                'verbose_name': '메시지 로그',
                'verbose_name_plural': '메시지 로그 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalSystemSetting',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=100, verbose_name='설정 키')),
                ('value', models.TextField(verbose_name='설정 값')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='설명')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='수정일')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='수정자')),
            ],
            options={
                'verbose_name': 'historical 시스템 설정',
                'verbose_name_plural': 'historical 시스템 설정 목록',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=200, verbose_name='파일명')),
                ('file_path', models.CharField(max_length=500, verbose_name='파일 경로')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='파일 크기 (bytes)')),
                ('status', models.CharField(choices=[('pending', '대기'), ('running', '진행 중'), ('completed', '완료'), ('failed', '실패')], default='pending', max_length=20, verbose_name='상태')),
                ('error_message', models.TextField(blank=True, verbose_name='오류 메시지')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='완료 시각')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
            ],
            options={
                'verbose_name': '백업',
                'verbose_name_plural': '백업 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
