# Generated by Django 4.2.27 on 2025-12-18 00:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('event_type', models.CharField(choices=[('class', '정규 수업'), ('makeup', '보강'), ('holiday', '휴원'), ('special', '특강'), ('camp', '캠프'), ('other', '기타')], default='class', max_length=20, verbose_name='유형')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('start_date', models.DateField(verbose_name='시작일')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='종료일')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='시작 시간')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='종료 시간')),
                ('all_day', models.BooleanField(default=False, verbose_name='종일')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='장소')),
                ('color', models.CharField(default='#4285f4', max_length=7, verbose_name='색상')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='반복 여부')),
                ('recurrence_rule', models.CharField(blank=True, help_text='RRULE 형식 (예: FREQ=WEEKLY;BYDAY=MO,WE,FR)', max_length=200, verbose_name='반복 규칙')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('assigned_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='classes.class', verbose_name='반')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_events', to='teachers.teacher', verbose_name='담당 강사')),
            ],
            options={
                'verbose_name': '캘린더 이벤트',
                'verbose_name_plural': '캘린더 이벤트 목록',
                'ordering': ['start_date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='MakeupClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_date', models.DateField(verbose_name='원래 수업일')),
                ('reason', models.TextField(verbose_name='보강 사유')),
                ('status', models.CharField(choices=[('scheduled', '예정'), ('completed', '완료'), ('cancelled', '취소')], default='scheduled', max_length=20, verbose_name='상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('makeup_event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='makeup_info', to='schedule.calendarevent', verbose_name='보강 일정')),
                ('original_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='makeup_classes', to='classes.class', verbose_name='원래 반')),
            ],
            options={
                'verbose_name': '보강 수업',
                'verbose_name_plural': '보강 수업 목록',
                'ordering': ['-original_date'],
            },
        ),
        migrations.CreateModel(
            name='HolidayRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('holiday_type', models.CharField(choices=[('regular', '정기 휴원'), ('national', '공휴일'), ('temporary', '임시 휴원'), ('other', '기타')], default='regular', max_length=20, verbose_name='유형')),
                ('start_date', models.DateField(verbose_name='시작일')),
                ('end_date', models.DateField(verbose_name='종료일')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('affects_all', models.BooleanField(default=True, verbose_name='전체 적용')),
                ('notify_parents', models.BooleanField(default=True, verbose_name='학부모 알림')),
                ('notified_at', models.DateTimeField(blank=True, null=True, verbose_name='알림 발송일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('affected_classes', models.ManyToManyField(blank=True, related_name='holidays', to='classes.class', verbose_name='적용 반')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
            ],
            options={
                'verbose_name': '휴원 기간',
                'verbose_name_plural': '휴원 기간 목록',
                'ordering': ['-start_date'],
            },
        ),
    ]
