# Generated by Django 4.2.27 on 2025-12-18 01:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0002_waitlist_consultlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('phone', models.CharField(max_length=20, verbose_name='연락처')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='이메일')),
                ('relationship', models.CharField(default='부모', help_text='예: 아버지, 어머니, 조부모 등', max_length=20, verbose_name='관계')),
                ('receive_attendance_alert', models.BooleanField(default=True, verbose_name='출결 알림 수신')),
                ('receive_payment_alert', models.BooleanField(default=True, verbose_name='수납 알림 수신')),
                ('receive_score_alert', models.BooleanField(default=True, verbose_name='성적 알림 수신')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('last_login_at', models.DateTimeField(blank=True, null=True, verbose_name='마지막 로그인')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('children', models.ManyToManyField(related_name='parent_accounts', to='students.student', verbose_name='자녀')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_account', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '학부모 계정',
                'verbose_name_plural': '학부모 계정 목록',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ParentMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('to_academy', '학원으로'), ('to_parent', '학부모에게')], max_length=20, verbose_name='방향')),
                ('subject', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('is_read', models.BooleanField(default=False, verbose_name='읽음')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='읽은 시각')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='parent_portal.parentaccount', verbose_name='학부모')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_messages', to='students.student', verbose_name='학생')),
            ],
            options={
                'verbose_name': '학부모 메시지',
                'verbose_name_plural': '학부모 메시지 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParentInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='초대 코드')),
                ('status', models.CharField(choices=[('pending', '대기'), ('used', '사용됨'), ('expired', '만료')], default='pending', max_length=20, verbose_name='상태')),
                ('expires_at', models.DateTimeField(verbose_name='만료일시')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='사용일시')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_invites', to='students.student', verbose_name='학생')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parent_portal.parentaccount', verbose_name='사용자')),
            ],
            options={
                'verbose_name': '학부모 초대',
                'verbose_name_plural': '학부모 초대 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
