# Generated by Django 4.2.27 on 2025-12-18 01:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0002_waitlist_consultlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='과목명')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='코드')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '과목',
                'verbose_name_plural': '과목 목록',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReportCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('monthly', '월간'), ('quarterly', '분기'), ('semester', '학기'), ('yearly', '연간')], default='monthly', max_length=20, verbose_name='기간 유형')),
                ('period_start', models.DateField(verbose_name='시작일')),
                ('period_end', models.DateField(verbose_name='종료일')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('total_exams', models.PositiveIntegerField(default=0, verbose_name='시험 수')),
                ('average_score', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='평균 점수')),
                ('teacher_comment', models.TextField(blank=True, verbose_name='강사 코멘트')),
                ('pdf_file', models.FileField(blank=True, upload_to='report_cards/', verbose_name='PDF 파일')),
                ('is_published', models.BooleanField(default=False, verbose_name='발급 완료')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='발급일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='students.student', verbose_name='학생')),
            ],
            options={
                'verbose_name': '성적표',
                'verbose_name_plural': '성적표 목록',
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='LearningGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='목표')),
                ('description', models.TextField(blank=True, verbose_name='상세 설명')),
                ('target_score', models.PositiveIntegerField(blank=True, null=True, verbose_name='목표 점수')),
                ('start_date', models.DateField(verbose_name='시작일')),
                ('end_date', models.DateField(verbose_name='종료일')),
                ('current_progress', models.PositiveIntegerField(default=0, verbose_name='진행률 (%)')),
                ('status', models.CharField(choices=[('active', '진행 중'), ('achieved', '달성'), ('failed', '미달성'), ('cancelled', '취소')], default='active', max_length=20, verbose_name='상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='설정자')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_goals', to='students.student', verbose_name='학생')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.subject', verbose_name='과목')),
            ],
            options={
                'verbose_name': '학습 목표',
                'verbose_name_plural': '학습 목표 목록',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='시험명')),
                ('exam_type', models.CharField(choices=[('monthly', '월간 테스트'), ('midterm', '중간고사'), ('final', '기말고사'), ('mock', '모의고사'), ('quiz', '쪽지시험'), ('other', '기타')], default='monthly', max_length=20, verbose_name='유형')),
                ('exam_date', models.DateField(verbose_name='시험일')),
                ('max_score', models.PositiveIntegerField(default=100, verbose_name='만점')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('is_published', models.BooleanField(default=False, help_text='학부모에게 공개', verbose_name='공개 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('assigned_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='classes.class', verbose_name='대상 반')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='academics.subject', verbose_name='과목')),
            ],
            options={
                'verbose_name': '시험',
                'verbose_name_plural': '시험 목록',
                'ordering': ['-exam_date'],
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='점수')),
                ('grade', models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-'), ('D+', 'D+'), ('D', 'D'), ('D-', 'D-'), ('F', 'F')], max_length=2, verbose_name='등급')),
                ('rank', models.PositiveIntegerField(blank=True, null=True, verbose_name='순위')),
                ('feedback', models.TextField(blank=True, verbose_name='피드백')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='academics.exam', verbose_name='시험')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='students.student', verbose_name='학생')),
            ],
            options={
                'verbose_name': '성적',
                'verbose_name_plural': '성적 목록',
                'ordering': ['-exam__exam_date', 'student__name'],
                'unique_together': {('exam', 'student')},
            },
        ),
    ]
