# Generated by Django 4.2.27 on 2025-12-18 01:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0001_initial'),
        ('students', '0002_waitlist_consultlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('student', '학생'), ('parent', '학부모'), ('class', '반 전체'), ('all', '전체')], default='student', max_length=20, verbose_name='대상 유형')),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='예약 발송일시')),
                ('status', models.CharField(choices=[('pending', '대기'), ('processing', '처리중'), ('sent', '발송완료'), ('failed', '실패'), ('cancelled', '취소')], default='pending', max_length=20, verbose_name='상태')),
                ('total_count', models.IntegerField(default=0, verbose_name='전체 건수')),
                ('success_count', models.IntegerField(default=0, verbose_name='성공 건수')),
                ('fail_count', models.IntegerField(default=0, verbose_name='실패 건수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='처리일')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('target_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.class', verbose_name='대상 반')),
                ('target_students', models.ManyToManyField(blank=True, related_name='notification_jobs', to='students.student', verbose_name='대상 학생')),
            ],
            options={
                'verbose_name': '알림 발송 작업',
                'verbose_name_plural': '알림 발송 작업 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='템플릿명')),
                ('code', models.CharField(help_text='시스템 식별용 코드', max_length=50, unique=True, verbose_name='코드')),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('kakao', '카카오 알림톡'), ('email', '이메일'), ('app', '앱 푸시')], default='sms', max_length=20, verbose_name='발송 채널')),
                ('trigger_type', models.CharField(choices=[('manual', '수동 발송'), ('unpaid', '미납 알림'), ('absent', '결석 알림'), ('consult_reminder', '상담 리마인더'), ('schedule_change', '일정 변경'), ('enrollment', '등록 완료'), ('payment_complete', '수납 완료')], default='manual', max_length=30, verbose_name='트리거 유형')),
                ('subject', models.CharField(blank=True, help_text='이메일 발송 시 사용', max_length=200, verbose_name='제목')),
                ('content', models.TextField(help_text='변수: {학생명}, {반명}, {금액}, {마감일}, {날짜} 등', verbose_name='내용')),
                ('auto_send', models.BooleanField(default=False, verbose_name='자동 발송')),
                ('days_before', models.IntegerField(blank=True, help_text='마감일 N일 전 자동 발송', null=True, verbose_name='N일 전 발송')),
                ('send_time', models.TimeField(blank=True, null=True, verbose_name='발송 시각')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
            ],
            options={
                'verbose_name': '알림 템플릿',
                'verbose_name_plural': '알림 템플릿 목록',
                'ordering': ['trigger_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=100, verbose_name='수신자명')),
                ('recipient_contact', models.CharField(max_length=100, verbose_name='수신 연락처')),
                ('sent_content', models.TextField(verbose_name='발송 내용')),
                ('result', models.CharField(choices=[('success', '성공'), ('failed', '실패')], max_length=20, verbose_name='결과')),
                ('error_message', models.TextField(blank=True, verbose_name='오류 메시지')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='발송 시각')),
                ('provider_response', models.TextField(blank=True, verbose_name='발송 응답')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='notifications.notificationjob', verbose_name='발송 작업')),
            ],
            options={
                'verbose_name': '알림 발송 로그',
                'verbose_name_plural': '알림 발송 로그 목록',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddField(
            model_name='notificationjob',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='notifications.notificationtemplate', verbose_name='템플릿'),
        ),
    ]
