# Generated by Django 4.2.27 on 2025-12-18 01:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0002_waitlist_consultlog'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('weekly', '주간'), ('monthly', '월간')], default='weekly', max_length=20, verbose_name='기간유형')),
                ('start_date', models.DateField(verbose_name='시작일')),
                ('end_date', models.DateField(verbose_name='종료일')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('attendance_total', models.IntegerField(default=0, verbose_name='총 수업일')),
                ('attendance_present', models.IntegerField(default=0, verbose_name='출석')),
                ('attendance_absent', models.IntegerField(default=0, verbose_name='결석')),
                ('attendance_late', models.IntegerField(default=0, verbose_name='지각')),
                ('exam_count', models.IntegerField(default=0, verbose_name='시험 수')),
                ('average_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='평균 점수')),
                ('learning_summary', models.TextField(blank=True, verbose_name='학습 내용')),
                ('teacher_comment', models.TextField(blank=True, verbose_name='강사 코멘트')),
                ('homework_status', models.TextField(blank=True, verbose_name='과제 현황')),
                ('next_plan', models.TextField(blank=True, verbose_name='다음주 계획')),
                ('status', models.CharField(choices=[('draft', '작성중'), ('ready', '발송대기'), ('sent', '발송완료')], default='draft', max_length=20, verbose_name='상태')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='발송일시')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reports', to='students.student', verbose_name='학생')),
            ],
            options={
                'verbose_name': '주간/월간 보고서',
                'verbose_name_plural': '주간/월간 보고서 목록',
                'ordering': ['-end_date', 'student'],
            },
        ),
    ]
