# Generated by Django 4.2.27 on 2025-12-13 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='날짜')),
                ('status', models.CharField(choices=[('present', '출석'), ('absent', '결석'), ('late', '지각'), ('early_leave', '조퇴')], default='present', max_length=20, verbose_name='출결 상태')),
                ('note', models.TextField(blank=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('assigned_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='classes.class', verbose_name='반')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='students.student', verbose_name='학생')),
            ],
            options={
                'verbose_name': '출결',
                'verbose_name_plural': '출결 목록',
                'ordering': ['-date', 'student__name'],
                'unique_together': {('student', 'date')},
            },
        ),
    ]
