# Generated by Django 4.2.27 on 2025-12-16 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0002_waitlist_consultlog'),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QrSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_date', models.DateField(verbose_name='수업일')),
                ('token', models.CharField(max_length=64, unique=True, verbose_name='토큰')),
                ('starts_at', models.DateTimeField(verbose_name='시작 시각')),
                ('expires_at', models.DateTimeField(verbose_name='만료 시각')),
                ('status', models.CharField(choices=[('active', '활성'), ('expired', '만료'), ('closed', '종료')], default='active', max_length=20, verbose_name='상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('assigned_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_sessions', to='classes.class', verbose_name='반')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
            ],
            options={
                'verbose_name': 'QR 세션',
                'verbose_name_plural': 'QR 세션 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QrScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(auto_now_add=True, verbose_name='스캔 시각')),
                ('result', models.CharField(choices=[('success', '성공'), ('fail', '실패')], max_length=20, verbose_name='결과')),
                ('fail_reason', models.CharField(blank=True, choices=[('invalid_token', '잘못된 토큰'), ('expired', '만료된 세션'), ('not_enrolled', '미등록 학생'), ('duplicate', '중복 출석'), ('unknown', '알 수 없음')], max_length=30, verbose_name='실패 사유')),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='클라이언트 IP')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User Agent')),
                ('qr_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_logs', to='attendance.qrsession', verbose_name='QR 세션')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_scans', to='students.student', verbose_name='학생')),
            ],
            options={
                'verbose_name': 'QR 스캔 로그',
                'verbose_name_plural': 'QR 스캔 로그 목록',
                'ordering': ['-scanned_at'],
            },
        ),
    ]
